from fpdf import FPDF
from . import defaults
import os

class PDF(FPDF):
    def __init__(self, title, logo):
        FPDF.__init__(self, orientation="L", format="A4")
        self.logo_loc = logo
        self.title_text = title
        self.set_font("Times", size=12)

    def header(self):
        # Rendering logo:
        self.image(self.logo_loc, 10, 8, 33)
        # Setting font: helvetica bold 15
        self.set_font("helvetica", "B", 15)
        # Moving cursor to the right:
        self.cell(80)
        # Printing title:
        self.cell(30, 10, self.title_text, 1, 0, "C")
        # Performing a line break:
        self.ln(40)

    def footer(self):
        # Position cursor at 1.5 cm from bottom:
        self.set_y(-15)
        # Setting font: helvetica italic 8
        self.set_font("helvetica", "I", 8)
        # Printing page number:
        self.cell(0, 10, f"Page {self.page_no()}/{{nb}}", 0, 0, "C")
        self.ln(5)
        self.cell(0, 10, f"Generated by the mouldController script environment", 0, 0, "C")

    def insert_text(self, text):
        self.cell(0, 10, text, 0, 1)

    def insert_graph(self, graph_loc):
        self.image(graph_loc, 80, 40, 210)
